// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khrtlxmwytymsitddkdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtocnRseG13eXR5bXNpdGRka2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Nzc5MzEsImV4cCI6MjA1OTM1MzkzMX0.jgbLy11fJ1vKzN2MC-1YLkXKPEnsG0_URIPY6yTGg2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);